package it.moda.dto;

// Generated 3-gen-2013 16.40.18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgendaDettaglioId generated by hbm2java
 */
@Embeddable
public class AgendaDettaglioDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7304304314317599044L;
	private Integer pgAge;
	private Integer mcod;
	private String pden;
	private String ptel;
	private Date dataora;
	private String ora;
	private String note;
	private String tiAge;
	private String tiOpeAge;
	private Boolean visita;
	private Date pnascita;

	public AgendaDettaglioDTO() {
	}

	public AgendaDettaglioDTO(Integer pgAge, Integer mcod, String pden,
			String ptel, Date dataora, String ora, String note, String tiAge,
			String tiOpeAge, Boolean visita, Date pnascita) {
		this.pgAge = pgAge;
		this.mcod = mcod;
		this.pden = pden;
		this.ptel = ptel;
		this.dataora = dataora;
		this.ora = ora;
		this.note = note;
		this.tiAge = tiAge;
		this.tiOpeAge = tiOpeAge;
		this.visita = visita;
		this.pnascita = pnascita;
	}

	@Column(name = "Pg_age")
	public Integer getPgAge() {
		return this.pgAge;
	}

	public void setPgAge(Integer pgAge) {
		this.pgAge = pgAge;
	}

	@Column(name = "mcod")
	public Integer getMcod() {
		return this.mcod;
	}

	public void setMcod(Integer mcod) {
		this.mcod = mcod;
	}

	@Column(name = "pden", length = 150)
	public String getPden() {
		return this.pden;
	}

	public void setPden(String pden) {
		this.pden = pden;
	}

	@Column(name = "PTEL", length = 60)
	public String getPtel() {
		return this.ptel;
	}

	public void setPtel(String ptel) {
		this.ptel = ptel;
	}

	@Column(name = "dataora", length = 19)
	public Date getDataora() {
		return this.dataora;
	}

	public void setDataora(Date dataora) {
		this.dataora = dataora;
	}

	@Column(name = "ORA", length = 5)
	public String getOra() {
		return this.ora;
	}

	public void setOra(String ora) {
		this.ora = ora;
	}

	@Column(name = "Note", length = 50)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "Ti_age", length = 1)
	public String getTiAge() {
		return this.tiAge;
	}

	public void setTiAge(String tiAge) {
		this.tiAge = tiAge;
	}

	@Column(name = "Ti_ope_age", length = 1)
	public String getTiOpeAge() {
		return this.tiOpeAge;
	}

	public void setTiOpeAge(String tiOpeAge) {
		this.tiOpeAge = tiOpeAge;
	}

	@Column(name = "Visita")
	public Boolean getVisita() {
		return this.visita;
	}

	public void setVisita(Boolean visita) {
		this.visita = visita;
	}

	@Column(name = "pnascita", length = 19)
	public Date getPnascita() {
		return this.pnascita;
	}

	public void setPnascita(Date pnascita) {
		this.pnascita = pnascita;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgendaDettaglioDTO))
			return false;
		AgendaDettaglioDTO castOther = (AgendaDettaglioDTO) other;

		return ((this.getPgAge() == castOther.getPgAge()) || (this.getPgAge() != null
				&& castOther.getPgAge() != null && this.getPgAge().equals(
				castOther.getPgAge())))
				&& ((this.getMcod() == castOther.getMcod()) || (this.getMcod() != null
						&& castOther.getMcod() != null && this.getMcod()
						.equals(castOther.getMcod())))
				&& ((this.getPden() == castOther.getPden()) || (this.getPden() != null
						&& castOther.getPden() != null && this.getPden()
						.equals(castOther.getPden())))
				&& ((this.getPtel() == castOther.getPtel()) || (this.getPtel() != null
						&& castOther.getPtel() != null && this.getPtel()
						.equals(castOther.getPtel())))
				&& ((this.getDataora() == castOther.getDataora()) || (this
						.getDataora() != null && castOther.getDataora() != null && this
						.getDataora().equals(castOther.getDataora())))
				&& ((this.getOra() == castOther.getOra()) || (this.getOra() != null
						&& castOther.getOra() != null && this.getOra().equals(
						castOther.getOra())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null
						&& castOther.getNote() != null && this.getNote()
						.equals(castOther.getNote())))
				&& ((this.getTiAge() == castOther.getTiAge()) || (this
						.getTiAge() != null && castOther.getTiAge() != null && this
						.getTiAge().equals(castOther.getTiAge())))
				&& ((this.getTiOpeAge() == castOther.getTiOpeAge()) || (this
						.getTiOpeAge() != null
						&& castOther.getTiOpeAge() != null && this
						.getTiOpeAge().equals(castOther.getTiOpeAge())))
				&& ((this.getVisita() == castOther.getVisita()) || (this
						.getVisita() != null && castOther.getVisita() != null && this
						.getVisita().equals(castOther.getVisita())))
				&& ((this.getPnascita() == castOther.getPnascita()) || (this
						.getPnascita() != null
						&& castOther.getPnascita() != null && this
						.getPnascita().equals(castOther.getPnascita())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPgAge() == null ? 0 : this.getPgAge().hashCode());
		result = 37 * result
				+ (getMcod() == null ? 0 : this.getMcod().hashCode());
		result = 37 * result
				+ (getPden() == null ? 0 : this.getPden().hashCode());
		result = 37 * result
				+ (getPtel() == null ? 0 : this.getPtel().hashCode());
		result = 37 * result
				+ (getDataora() == null ? 0 : this.getDataora().hashCode());
		result = 37 * result
				+ (getOra() == null ? 0 : this.getOra().hashCode());
		result = 37 * result
				+ (getNote() == null ? 0 : this.getNote().hashCode());
		result = 37 * result
				+ (getTiAge() == null ? 0 : this.getTiAge().hashCode());
		result = 37 * result
				+ (getTiOpeAge() == null ? 0 : this.getTiOpeAge().hashCode());
		result = 37 * result
				+ (getVisita() == null ? 0 : this.getVisita().hashCode());
		result = 37 * result
				+ (getPnascita() == null ? 0 : this.getPnascita().hashCode());
		return result;
	}

}
